//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.Tea.DataModel.SqlModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Province
    {
        [Key]
        public int ProvinceID { get; set; }
        public string ProvinceCode { get; set; }
        public string ProvinceName { get; set; }
        public string ShortName { get; set; }
        public string LNG { get; set; }
        public string LAT { get; set; }
        public string Sort { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
    }
}
