//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WK.Tea.DataModel.SqlModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class T_Shop
    {
        [Key]
        public int ID { get; set; }
        public string ShopName { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string ShopAddress { get; set; }
        public Nullable<decimal> LNG { get; set; }
        public Nullable<decimal> LAT { get; set; }
        public string ShopPhoneNum { get; set; }
        public string ShopContacts { get; set; }
        public string BuildNo { get; set; }
        public string FloorNo { get; set; }
        public string RoomNo { get; set; }
        public Nullable<byte> Flag { get; set; }
        public Nullable<System.DateTime> CTime { get; set; }

        public string CleanerOpenID { get; set; }

        public Nullable<decimal> OrderFee { get; set; }
        public Nullable<decimal> ReOrderFee { get; set; }

        public Nullable<short> LockType { get; set; }
        public string LockID { get; set; }
    }
}
